name: 02 - work flows
on:
  push:
  pull_request:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "iv been triggered by a(n) ${{ github.event_name }} event."