name: 04 - using actions
 
on: push

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: ls    
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
               node-version: '22.x'
            - name: Install Dependencies
              run: npm ci
              working-directory: 04-using-actions/reactapp

         # 0. checkout the code from repo    
         # 1. install deps of react apps
         # 2. excute automated tasks
    