name: 11 - Working with Inputs

on:
    workflow_dispatch:
        inputs:
          dry-run: 
            type: boolean
            description: skip deployment and only print build output
            default: false
          target:
            type: environment
            required: true
            description: which env the workflow will target
          tag:
            type: choice
            options:
              - v1
              - v2
              - v3
            default: v3
            description: release from which to build and deploy


jobs:
   build: 
     runs-on: ubuntu-latest
     steps:
        - name: build
          run: echo "building from ${{ inputs.tag }}"
   deploy: 
      runs-on: ubuntu latest
      if: ${{ !inputs.dry-run }}
      environment: ${{ inputs.target }}
      steps:
        - name: deploy
          run: echo "deploying to ${{ inputs.target }}"
