name: 15 - Working with Matrices
on: 
    workflow_dispatch:


jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
             fail-fast: false
             matrix:
                node-version: [20.x, 21.x, 22.x]
                os: 
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      node-version: 18.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        steps:
                    - name: setup node
                      uses: actions/setup-node@v4
                      with:  ${{ matrix.node-version }}
                    - name: fail if experimental
                      if: matrix.tag == 'experimental'
                      run: exit 1
                    - name: perform some tests
                      run: |
                        echo "running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
                        sleep 10
                    - name: upload test results
                      run: echo "uploading test results"