name: 17 - custom-actions - composite

on: 
    workflow_dispatch:

env: 
    working-directory: 04-using-actions/reactapp
    
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: ${{ env.working-directory }}

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                 node-version: 22.x
                 working-dir: ${{ env.working-directory }}
            - name: test
              run: npm run test
              working-directory: ${{ env.working-directory }}
            - name: build
              run: npm run build
              