name: 20 - 2 - Managing Concurrency

on:
    workflow_dispatch:

jobs:
    ping-with-concurrency:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
           - uses: actions/checkout@v4
           - name: ping to url 
             id: ping-url
             uses: ./.github/actions/docker-ping-url
             with:
               url: https://www.mahmoud.com
               max_trials: 20
               delay: 5

    ping-without-concurrency:
        runs-on: ubuntu-latest
         
        steps:
             - uses: actions/checkout@v4
             - name: ping to url 
               id: ping-url
               uses: ./.github/actions/docker-ping-url
               with:
                 url: https://www.mahmoud.com
                 max_trials: 20
                 delay: 5
